// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVqLUuA5yotTRf-P--3eGpLeImL0B6IHo',
    appId: '1:1042033995153:web:ac8d200155f120b081fe30',
    messagingSenderId: '1042033995153',
    projectId: 'trackcase12',
    authDomain: 'trackcase12.firebaseapp.com',
    storageBucket: 'trackcase12.appspot.com',
    measurementId: 'G-CF762JBDRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsH1jK7nQozkNRjTOQc8RxBeamkLAh_aw',
    appId: '1:1042033995153:android:45c4f4fbdea6590181fe30',
    messagingSenderId: '1042033995153',
    projectId: 'trackcase12',
    storageBucket: 'trackcase12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBA-zW451fQmF5sQJmPsvBUMB4GV-zZe4',
    appId: '1:1042033995153:ios:9bd4b11dc583bb2b81fe30',
    messagingSenderId: '1042033995153',
    projectId: 'trackcase12',
    storageBucket: 'trackcase12.appspot.com',
    iosBundleId: 'com.example.trackcase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBA-zW451fQmF5sQJmPsvBUMB4GV-zZe4',
    appId: '1:1042033995153:ios:9bd4b11dc583bb2b81fe30',
    messagingSenderId: '1042033995153',
    projectId: 'trackcase12',
    storageBucket: 'trackcase12.appspot.com',
    iosBundleId: 'com.example.trackcase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVqLUuA5yotTRf-P--3eGpLeImL0B6IHo',
    appId: '1:1042033995153:web:0f533113b328549f81fe30',
    messagingSenderId: '1042033995153',
    projectId: 'trackcase12',
    authDomain: 'trackcase12.firebaseapp.com',
    storageBucket: 'trackcase12.appspot.com',
    measurementId: 'G-7Y9GKPK5XE',
  );
}
